export const environment = {
  production: false,
  APP_NAME: 'fullstack',
  API_PREFIX: 'api',
  API_PORT: 4201,
  API_DOMAIN: 'localhost',
  PWA_PORT: 4200,
  PWA_DOMAIN: 'localhost',
  DB_PORT: 4202,
  DB_DOMAIN: 'localhost',
  DB_NAME: 'test',
  DB_USER: 'test',
  DB_PASSWORD: 'test',
  JWT_USER_KEY: 'test',
  JWT_EMAIL_KEY: 'test',
  EMAIL_HOST: 'smtp.ethereal.email',
  EMAIL_PORT: 587,
  EMAIL_SECURE: false,
  EMAIL_USER: 0,
  EMAIL_PASS: 0,
  EMAIL_FROM: '${PROJECT_NAME} <foo@example.com>',
};
