export const environment = {
  production: true,
  APP_NAME: 'fullstack',
  API_PORT: 3333,
  API_DOMAIN: 'localhost',
  PWA_PORT: 80,
  PWA_DOMAIN: 'localhost',
  DB_PORT: 5432,
  DB_DOMAIN: 'db',
  DB_NAME: 'postgres',
  DB_USER: 'changeme',
  DB_PASSWORD: 'changeme',
  JWT_USER_KEY: 'changeme',
  JWT_EMAIL_KEY: 'changeme',
  EMAIL_HOST: 'smtp.ethereal.email',
  EMAIL_PORT: 587,
  EMAIL_SECURE: false,
  EMAIL_USER: 0,
  EMAIL_PASS: 0,
  EMAIL_FROM: '${PROJECT_NAME} <foo@example.com>',
};
